agenda/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from agenda.views import *
from usuarios.views import RegistrarUsuarioView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', index, name='index'),
    path('insAgenda/', insAgenda, name='edit'),
    path('editAgenda/', editAgenda, name='edit'),
    path('delAgenda/', delAgenda, name='edit'),
    re_path(r'^registrar/$', RegistrarUsuarioView.as_view(), name='registrar'),
    re_path(r'^login/$', auth_views.login, {'template_name':'login.html'}, name='login'),
    re_path(r'^logout/$', auth_views.logout, {'next_page':'/'}, name='logout')
]

agendainfo/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('agenda.urls'))
]

usuarios/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from usuarios.views import RegistrarUsuarioView
from django.contrib.auth import views as auth_views
from usuarios.views import RegistrarUsuarioView

urlpatterns = [
    re_path(r'^registrar$', RegistrarUsuarioView.as_view(), name='registrar'),
    re_path(r'^login$', auth_views.login, {'template_name':'login.html'}, name='login'),
    re_path(r'^logout$', auth_views.logout, {'next_page':'/'}, name='logout')
]

agenda/models.py
from django.db import models

# Create your models here.
#class Paciente(models.Model):

#	nome = models.CharField(max_length=255, null=False)
#	idade = models.DecimalField(max_digits=5, null=False, decimal_places=3)
#	telefone = models.CharField(max_length=255, null=False)
#	email = models.EmailField()

class Agenda(models.Model):

	agd_date = models.CharField(max_length=255, null=False)
	agd_hora_inicio = models.CharField(max_length=255, null=False)
	agd_hora_fim = models.CharField(max_length=255, null=False)
	agd_paciente = models.CharField(max_length=255, null=False)
	agd_procedimento = models.CharField(max_length=255, null=False)

	def get_date(self):
		return self.agd_date

usuarios/models.py
from django.db import models

# Create your models here.

agenda/forms.py
from django import forms
from django.db import models
#from django.contrib.auth.models import User

class EditAgendaForm(forms.Form):

	id = 11111111
	date = models.DateField(null=False)
	hora_inicio = models.TimeField(null=False)
	hora_fim = models.TimeField(null=False)
	paciente = models.CharField(max_length=255, null=False)
	procedimento = models.CharField(max_length=255, null=False)


	

usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):

	nome = forms.CharField(required=True)
	email = forms.EmailField(required=True)
	senha = forms.CharField(required=True)
	telefone = forms.CharField(required=True)
	nome_empresa = forms.CharField(required=True)

	def is_valid(self):
		valid = True
		if not super(RegistrarUsuarioForm, self).is_valid():
			self.adiciona_erro('Por favor, verifique os dados informados')
			valid = False

		user_exists = User.objects.filter(username=self.data['nome']).exists()

		if user_exists:
			self.adiciona_erro('Usuario ja existene')
			valid = False

		return valid

	def adiciona_erro(self, message):
		errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
		errors.append(message)

agenda/views.py
from django.shortcuts import get_object_or_404,render, redirect
from django.utils.dateparse import parse_datetime
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.template import defaultfilters
from django.views.generic.base import View
from agenda.forms import EditAgendaForm
from agenda.models import Agenda

# Create your views here.
@login_required
def index(request):
	all_data = Agenda.objects.all()
	stu = { "agendamentos" : all_data }

	#return HttpResponse(html)
	return render(request, 'index.html', stu )

def logout(request):
	return HttpResponse('Fez logout')


def insAgenda(request):

	ins_date 		 = request.POST['dt_agenda']
	ins_hora_inicio  = request.POST['hh_inicio']
	ins_hora_fim 	 = request.POST['hh_fim']
	ins_paciente 	 = request.POST['paciente']
	ins_procedimento = request.POST['proced']

	agenda = Agenda(agd_date=ins_paciente, agd_hora_inicio=ins_hora_inicio,agd_hora_fim=ins_hora_fim,agd_paciente=ins_paciente,agd_procedimento=ins_procedimento)
	agenda.save()

	return HttpResponseRedirect('/')

def editAgenda(request):

	agenda 					= Agenda.objects.get(id=request.POST['id_agenda'])
	agenda.agd_date 		= request.POST['dt_agenda']
	agenda.agd_hora_inicio 	= request.POST['hh_inicio']
	agenda.agd_hora_fim 	= request.POST['hh_fim']
	agenda.agd_paciente 	= request.POST['paciente']
	agenda.agd_procedimento = request.POST['proced']
	agenda.save()

	return HttpResponseRedirect('/')

def delAgenda(request):

	agenda = Agenda.objects.get(id=request.POST['id_agenda']).delete()
	print("delete")

	return redirect('index')

agendainfo/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
	pass
	#return render(request, 'index.html')

usuarios/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.views.generic.base import View
#from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm
from django.http import HttpResponse


# Create your views here.
class RegistrarUsuarioView(View):

	template_name = 'registrar.html'

	def get(self, request):
		return render(request, self.template_name)

	def post(self, request):
		form = RegistrarUsuarioForm(request.POST)

		if form.is_valid():

			dados_form = form.data

			usuario = User.objects.create_user(dados_form['nome'], dados_form['email'], dados_form['senha'])
			
			return redirect('index')

		return render(request, self.template_name, {'form' : form})

agenda/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel= "stylesheet" href= "{% static 'css/bootstrap.min.css' %}"> 
    <link rel= "stylesheet" href= "{% static 'css/bootstrap-theme.min.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/main.css' %}" >
    <link rel="stylesheet" href="{% static 'css/all.css' %}" >
    <script src="{% static 'js/jquery-1.12.3.js' %} "></script>
    <script src="{% static 'js/bootstrap.min.js' %} "></script>
   
    <title>Agendamento de Pacientes</title>
  </head>
  <body>

    <main>
    <div class="container">

      <div class="header">
        <h3 class="text-muted">Agendamento de Pacientes</h3>
        <ul class="nav nav-pills pull-right">
          <li class="nav-link active"><a id="novaAgenda" href="">Novo agendamento</a></li>
          <li class=""><a href="{% url 'index' %}">{{usuario}}</a></li>
          <li class=""><a href="logout">Logout</a></li>
        </ul>
      </div>
    

      <div class="row content">
         {% block body %}
         {% endblock %}               
      </div>
    </div>
  </main>

  </body>
</html>

agenda/templates/base_usuario.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">

        <title>Agendamento On-Line</title>

        <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "css/signin.css" %}" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            {% block body %}

            {% endblock %} 
        </div>
    </body>
</html>

agenda/templates/index.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12">

        <div class="panel-heading">
            <table class="table table-hover">
			    <thead>
			      <tr>
			        <th>Data</th>
			        <th>Hora Início</th>
			        <th>Hora Fim</th>
			        <th>Paciente</th>
			        <th>Procedimento</th>
			        <th></th>
			        <th></th>
			      </tr>
			    </thead>
			    <tbody id="tabela-pacientes">
			    	<input type="hidden" id="token" value="{{ csrf_token }}">
			    	{% for item in agendamentos %}
			        <tr class="paciente">
			     	    <td id="data">{{ item.agd_date }}</td>
				        <td id="hora_inicio">{{ item.agd_hora_inicio }}</td>
				        <td id="hora_fim">{{ item.agd_hora_fim }}</td>
				        <td id="paciente">{{ item.agd_paciente }}</td>
				        <td id="procedimento">{{ item.agd_procedimento }}</td>
				        <td>
				        	<i class="fa fa-trash" id="{{item.id}}"></i>
				        </td>
				        <td>
				        	<i class="far fa-edit" id="{{item.id}}"></i>
				        </td>
				     </tr>
			        {% endfor %}
			    </tbody>
			</table>
        </div>
    </div>
</div>

{% block modal_edit %}
   {% include "modal/modal_edit.html" %}
{% endblock %}  

{% block modal_cad %}
   {% include "modal/modal_cad.html" %}
{% endblock %} 

{% load staticfiles %}
<script src="{% static 'js/lista_pacientes/pacientes.js' %}"></script>


<script>
/*
	#############################################
	AJAX para capturar o click no icone de editar
	#############################################
*/
/*var pacientes = document.querySelectorAll(".paciente");
var tabela = document.querySelector("#tabela-pacientes");

tabela.addEventListener("click", function(event) {

	tr = ((event.target.parentNode).parentNode)
	td = event.target.parentNode.className

	if(td == 'edit_icon'){

		data_agenda= 			tr.querySelector("#data").textContent,
	    hora_inicio_agenda= 	tr.querySelector("#hora_inicio").textContent,
	    hora_fim_agenda= 		tr.querySelector("#hora_fim").textContent,
	    paciente_agenda= 		tr.querySelector("#paciente").textContent,
	    procedimento_agenda= 	tr.querySelector("#procedimento").textContent

		$.ajax({
	    	method: "POST",
	    	url: "editAgenda/",
	    	data: {
	    		csrfmiddlewaretoken: 	"{{ csrf_token }}",
	    		id_agenda: 				event.target.parentNode.id,
	    		data_agenda: 			data_agenda,
	    		hora_inicio_agenda: 	hora_inicio_agenda,
	    		hora_fim_agenda: 		hora_fim_agenda,
	    		paciente_agenda: 		paciente_agenda,
	    		procedimento_agenda: 	procedimento_agenda
	    	}
	    });
	}
}); */
</script>

{% endblock %}

agenda/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}

    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Por favor, verifique o Email e/ou Senha informados
          </div>
        {% endif %}

        <a href="{% url 'registrar' %}">registre-se</a>
    </form>

{% endblock %}

agenda/templates/modal/modal_cad.html
<!-- Modal -->
    <div class="modal fade" id="myModalCad" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title">Novo agendamento</h4>
	        </div>
	        <div class="modal-body">
	        	<form id="cadastro" >
    				<fieldset>
    					<div class="form-group">
						    <label for="data">Data</label>
							<input class="form-control" name="modal_data_cad" id="modal_data_cad" type="text" required autofocus placeholder="__/__/____">
						</div>

						<div class="form-group">
							<label for="hora_inicio">Hora Início</label>
							<input class="form-control" name="modal_hora_inicio_cad" id="modal_hora_inicio_cad" type="datetime" required="required" maxlength="8" pattern="[0-9]{2}:[0-9]{2} [0-9]{2}$" autofocus placeholder="00:00:00">
						</div>

						<div class="form-group">
							<label for="hora_fim">Hora Fim</label>
							<input class="form-control" name="modal_hora_fim_cad" id="modal_hora_fim_cad" type="datetime" required="required" maxlength="8" pattern="[0-9]{2}:[0-9]{2} [0-9]{2}$" placeholder="00:00:00" autofocus>
						</div>

						<div class="form-group">
							<label for="paciente">Paciente</label>
							<input class="form-control" name="modal_paciente_cad" id="modal_paciente_cad" type="text" required="required" autofocus placeholder="Digite o nome do paciente">
						</div>

						<div class="form-group">
							<label for="procedimento">Procedimento</label>
	    					<textarea class="form-control" name="modal_procedimento_cad" id="modal_procedimento_cad" cols="60" rows="10" placeholder="Digite o procedimento" required autofocus></textarea>
	    				</div>
					</fieldset>
					<input type="hidden" name="codigo" id="codigo">
	        	</form>
	        </div>
	        <div class="modal-footer">
	          <button type="button" id="fecharCad" class="btn btn-default" data-dismiss="modal">Fechar</button>
	          <button type="submit" id="salvarCad" class="btn btn-primary" >Salvar</button>
	        </div>
        </div>
    </div>
    </div>

agenda/templates/modal/modal_edit.html
<!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
	        <div class="modal-header">
	          <button type="button" class="close" data-dismiss="modal">&times;</button>
	          <h4 class="modal-title">Editar agendamento</h4>
	        </div>
	        <div class="modal-body">
	        	<form action="index_submit" method="post">
    				<fieldset>
    					<div class="form-group">
						    <label for="data">Data</label>
							<input class="form-control" name="modal_data" id="modal_data" type="text" required autofocus>
						</div>

						<div class="form-group">
							<label for="hora_inicio">Hora Início</label>
							<input class="form-control" name="modal_hora_inicio" id="modal_hora_inicio" type="datetime" required autofocus>
						</div>

						<div class="form-group">
							<label for="hora_fim">Hora Fim</label>
							<input class="form-control" name="modal_hora_fim" id="modal_hora_fim" type="datetime" required autofocus>
						</div>

						<div class="form-group">
							<label for="paciente">Paciente</label>
							<input class="form-control" name="modal_paciente" id="modal_paciente" type="text" required autofocus pattern="[0-9]*" title="Preencha somente com números">
						</div>

						<div class="form-group">
							<label for="procedimento">Procedimento</label>
	    					<textarea class="form-control" name="modal_procedimento" id="modal_procedimento" cols="60" rows="10" placeholder="Digite o procedimento" required autofocus></textarea>
	    				</div>
					</fieldset>
					<input type="hidden" name="codigo" id="codigo">
	        	</form>
	        </div>
	        <div class="modal-footer">
	          <button type="button" id="fechar" class="btn btn-default" data-dismiss="modal">Fechar</button>
	          <button type="button" id="salvar" class="btn btn-primary" data-dismiss="modal">Salvar</button>
	        </div>
        </div>
    </div>
    </div>

agenda/templates/registrar.html
{% extends "base_usuario.html" %}

{% block body %}

  <form class="form-signin" action="{% url 'registrar' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Crie seu usuário</h2>

    <input type="text" id="id_email" name="email" class="form-control" placeholder="Email *" required autofocus>

    <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome *" required >

    <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *" required>

    <hr />

    <input type="text" id="id_telefone" name="telefone" class="form-control" placeholder="Telefone">

    <input type="text" id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa">

    <hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

    {% if form.errors %}
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{form.non_field_errors}}
      </div>
    {% endif %}
    
  </form>

{% endblock %}

agendainfo/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "styles/main.css" %}" rel="stylesheet">
    <title>Agendamento de Pacientes</title>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <ul class="nav nav-pills pull-right">
          <li class=""><a href="{% url 'index' %}">{{perfil_logado.nome}}</a></li>
          <li class=""><a href="/logout/">Logout</a></li>
        </ul>
        <h3 class="text-muted">ConnectedIn</h3>
      </div>

      <div class="row content">
         {% block body %}
         {% endblock %}               
      </div>
    </div>
  </body>
</html>

agendainfo/templates/index.html
{% extends "base.html" %}

{% block body %}
<div class="col-lg-12">

    <div class="panel panel-default">
        <div class="panel-heading">
            <strong>Listagem da agenda</strong>
        </div>
     
    </div>

</div>
{% endblock %}

usuarios/templates/base_usuario.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">

        <title>ConnectedIn</title>

        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/signin.css" %}" rel="stylesheet">
    </head>

    <body>
        <div class="container">
            {% block body %}

            {% endblock %} 
        </div>
    </body>
</html>

usuarios/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}

    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Por favor, verifique o Email e/ou Senha informados
          </div>
        {% endif %}

        <a href="{% url 'registrar' %}">registre-se</a>
    </form>

{% endblock %}

usuarios/templates/registrar.html
{% extends "base_usuario.html" %}

{% block body %}

  <form class="form-signin" action="{% url 'registrar' %}" method="post">
    {% csrf_token %}
    <h2 class="form-signin-heading">Crie seu usuário</h2>

    <input type="text" id="id_email" name="email" class="form-control" placeholder="Email *" required autofocus>

    <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome *" required >

    <input type="password" id="id_senha" name="senha" class="form-control" placeholder="Senha *" required>

    <hr />

    <input type="text" id="id_telefone" name="telefone" class="form-control" placeholder="Telefone">

    <input type="text" id="id_nome_empresa" name="nome_empresa" class="form-control" placeholder="Empresa">

    <hr />

    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Registrar</button>

    {% if form.errors %}
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{form.non_field_errors}}
      </div>
    {% endif %}
    
  </form>

{% endblock %}